"""Добавлены столбцы филиал, лесничество, квартал, выдел, ущерб (тенге), затраты на тушение

Revision ID: 1e5142ce68b1
Revises: b4e2298aa93a
Create Date: 2024-11-18 18:03:12.421590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e5142ce68b1'
down_revision = 'b4e2298aa93a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fires', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('forestry', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('quarter', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('allotment', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('damage_tenge', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('firefighting_costs', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fires', schema=None) as batch_op:
        batch_op.drop_column('firefighting_costs')
        batch_op.drop_column('damage_tenge')
        batch_op.drop_column('allotment')
        batch_op.drop_column('quarter')
        batch_op.drop_column('forestry')
        batch_op.drop_column('branch')

    # ### end Alembic commands ###
