"""Add edited_by_engineer to Fire

Revision ID: 26c3c43f1a58
Revises: db599aa3484a
Create Date: 2024-10-29 00:29:17.236243

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '26c3c43f1a58'
down_revision = 'db599aa3484a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('damage_area', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('damage_les', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('damage_les_lesopokryt', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('damage_les_verh', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('damage_not_les', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('APS_flag', sa.Boolean(), nullable=True),
    sa.Column('APS_people_count', sa.Integer(), nullable=True),
    sa.Column('APS_tecnic_count', sa.Integer(), nullable=True),
    sa.Column('APS_aircraft_count', sa.Integer(), nullable=True),
    sa.Column('KPS_flag', sa.Boolean(), nullable=True),
    sa.Column('KPS_people_count', sa.Integer(), nullable=True),
    sa.Column('KPS_tecnic_count', sa.Integer(), nullable=True),
    sa.Column('KPS_aircraft_count', sa.Integer(), nullable=True),
    sa.Column('MIO_flag', sa.Boolean(), nullable=True),
    sa.Column('MIO_people_count', sa.Integer(), nullable=True),
    sa.Column('MIO_tecnic_count', sa.Integer(), nullable=True),
    sa.Column('MIO_aircraft_count', sa.Integer(), nullable=True),
    sa.Column('other_org_flag', sa.Boolean(), nullable=True),
    sa.Column('other_org_people_count', sa.Integer(), nullable=True),
    sa.Column('other_org_tecnic_count', sa.Integer(), nullable=True),
    sa.Column('other_org_aircraft_count', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('edited_by_engineer', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('fire')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fire',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('region', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('damage_area', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('damage_les', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('file_path', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('damage_les_lesopokryt', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('damage_les_verh', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('damage_not_les', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('APS_flag', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('APS_people_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('APS_tecnic_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('APS_aircraft_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('KPS_flag', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('KPS_people_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('KPS_tecnic_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('KPS_aircraft_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('MIO_flag', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('MIO_people_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('MIO_tecnic_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('MIO_aircraft_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('other_org_flag', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('other_org_people_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('other_org_tecnic_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('other_org_aircraft_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('fires')
    # ### end Alembic commands ###
