"""Добавлены новые столбцы для APS, KPS, MIO и других организаций

Revision ID: db599aa3484a
Revises: 7713ed7ffb41
Create Date: 2024-10-26 22:24:45.225115

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db599aa3484a'
down_revision = '7713ed7ffb41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fire', schema=None) as batch_op:
        batch_op.alter_column('region',
               existing_type=mysql.ENUM('Акмолинская область', 'Атырауская область', 'Алматинская область', 'Актюбинская область', 'Восточно-Казахстанская область', 'Жамбылская область', 'Западно-Казахстанская область', 'Карагандинская область', 'Костанайская область', 'Кызылординская область', 'Мангыстауская  область', 'Павлодарская область', 'Северо-Казахстанская область', 'Туркестанская область', 'Область Абай', 'Область Жетысу', 'Область Улытау', 'г. Астана', 'г. Алматы', 'г. Шымкент'),
               type_=sa.String(length=255),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=150),
               nullable=False)
        batch_op.alter_column('roles',
               existing_type=mysql.ENUM('admin', 'operator', 'engineer'),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('region',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('region',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('roles',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('admin', 'operator', 'engineer'),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('fire', schema=None) as batch_op:
        batch_op.alter_column('region',
               existing_type=sa.String(length=255),
               type_=mysql.ENUM('Акмолинская область', 'Атырауская область', 'Алматинская область', 'Актюбинская область', 'Восточно-Казахстанская область', 'Жамбылская область', 'Западно-Казахстанская область', 'Карагандинская область', 'Костанайская область', 'Кызылординская область', 'Мангыстауская  область', 'Павлодарская область', 'Северо-Казахстанская область', 'Туркестанская область', 'Область Абай', 'Область Жетысу', 'Область Улытау', 'г. Астана', 'г. Алматы', 'г. Шымкент'),
               nullable=True)

    # ### end Alembic commands ###
