version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=rds
    depends_on:
      db:
        condition: service_healthy  # Ждём, пока база станет "healthy"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s              # Проверяем каждые 30 секунд
      timeout: 5s                # Таймаут запроса — 5 секунд
      retries: 3                 # 3 попытки до провала
      start_period: 30s          # Даём 30 секунд на запуск перед проверками

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=rds
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppassword"]
      interval: 30s              # Проверяем каждые 30 секунд
      timeout: 5s                # Таймаут — 5 секунд
      retries: 3                 # 3 попытки
      start_period: 30s          # Даём 30 секунд на старт