[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
PORT = "5000"
DB_HOST = "${{ Railway.MYSQL_HOST }}"
DB_USER = "${{ Railway.MYSQL_USER }}"
DB_PASSWORD = "${{ Railway.MYSQL_PASSWORD }}"
DB_NAME = "${{ Railway.MYSQL_DATABASE }}"
PYTHON_VERSION = "3.9"
DATABASE_URL = "${{Mysql.DATABASE_URL}}"